"""
SQL Query DB Call Node - Phase 2
==================================

Executes the SQL query generated by `sql_query_create_node` and returns formatted results.
Handles ALL tables dynamically (notices, class_captains, teachers, etc.)

Flow: sql_query.query_str → execute_query → contexts (formatted data)
"""

import sys
from pathlib import Path

project_root = Path(__file__).resolve().parent.parent
plan_root = project_root.parent / "plan"
if str(plan_root) not in sys.path:
    sys.path.insert(0, str(plan_root))
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

from state import RAGState
from utils.db_utils import execute_query

def sql_query_db_call_node(state: RAGState) -> dict:
    """
    Executes the generated SQL query and formats the results dynamically.
    
    Handles any table - automatically adapts to returned columns.
    """
    sql_query_state = state.get("sql_query", {})
    query = sql_query_state.get("query_str", "").strip()
    
    if not query:
        print("[sql_query_db_call] No query found in state")
        return {
            "sql_query": {
                **sql_query_state,
                "row_count": 0,
                "raw_context": "",
                "contexts": [],
                "context_found": False
            }
        }
    
    # Strip markdown block formatting if present
    if query.startswith("```sql"):
        query = query[6:].strip()
        if query.endswith("```"):
            query = query[:-3].strip()
    elif query.startswith("```"):
        query = query[3:].strip()
        if query.endswith("```"):
            query = query[:-3].strip()
    
    print(f"[sql_query_db_call] Executing SQL query...")
    print(f"[sql_query_db_call] Query: {query[:100]}...")
            
    try:
        results = execute_query(query, fetch=True)
        # execute_query returns list of dicts if fetch=True
        row_count = len(results) if isinstance(results, list) else 0
        
        if row_count == 0:
            print(f"[sql_query_db_call] No results found")
            return {
                "sql_query": {
                    **sql_query_state,
                    "row_count": 0,
                    "raw_context": "",
                    "contexts": [],
                    "context_found": False
                }
            }
        
        print(f"[sql_query_db_call] Retrieved {row_count} row(s)")
        
        # ★ DYNAMIC FORMATTING - works with ANY table
        raw_context_parts = []
        processed_contexts = []
        
        for i, row in enumerate(results, 1):
            # Raw context for debugging
            raw_context_parts.append(f"--- Row {i} ---")
            row_str = ", ".join(f"{k}: {str(v) if v is not None else 'NULL'}" for k, v in row.items())
            raw_context_parts.append(row_str)
            
            # ★ Processed context - keep ALL columns dynamically
            context_data = {"rank": i}
            for key, value in row.items():
                context_data[key] = str(value) if value is not None else ""
            
            processed_contexts.append(context_data)
            
            # Log preview - show first field value
            first_value = next((str(v)[:50] for v in row.values() if v), "Empty")
            print(f"  [{i}] Row: {first_value}...")
        
        raw_context = "\n".join(raw_context_parts)
            
        return {
            "sql_query": {
                **sql_query_state,
                "row_count": row_count,
                "raw_context": raw_context,
                "contexts": processed_contexts,
                "context_found": True
            }
        }
    except Exception as e:
        error_msg = f"SQL execution error: {str(e)}"
        print(f"[sql_query_db_call] {error_msg}")
        import traceback
        traceback.print_exc()
        
        return {
            "sql_query": {
                **sql_query_state,
                "row_count": 0,
                "raw_context": f"Error: {e}",
                "contexts": [],
                "context_found": False
            }
        }