"""
SQL Query DB Call Node - Phase 2
==================================

Executes the SQL query generated by `sql_query_create_node` and returns raw results.
Used in both the main phase (via `_route_after_sql`) and Phase 5 hybrid sub-queries.

The "select_query" field is created during create SQL call and verified before execution through db_utils.
When calling execute_query with fetch=True, it returns a list of dicts (one per row).
Determine if row count > expected_answer_length. If so record "raw_context" with formatted rows:
--- Row 1 ---
id: 1, department: CSE, course_name: Introduction...
"""

import sys
from pathlib import Path

project_root = Path(__file__).resolve().parent.parent
plan_root = project_root.parent / "plan"
if str(plan_root) not in sys.path:
    sys.path.insert(0, str(plan_root))
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

from state import RAGState
from utils.db_utils import execute_query

def sql_query_db_call_node(state: RAGState) -> dict:
    """
    Executes the generated SQL query and updates the state with the raw results.
    """
    sql_query_state = state.get("sql_query", {})
    query = sql_query_state.get("query_str", "").strip()
    
    if not query:
        return {"sql_query": {"row_count": 0, "raw_context": ""}}
    
    # Strip markdown block formatting if present
    if query.startswith("```sql"):
        query = query[6:].strip()
        if query.endswith("```"):
            query = query[:-3].strip()
    elif query.startswith("```"):
        query = query[3:].strip()
        if query.endswith("```"):
            query = query[:-3].strip()
            
    try:
        results = execute_query(query, fetch=True)
        # execute_query returns list of dicts if fetch=True
        row_count = len(results) if isinstance(results, list) else 0
        raw_context = ""
        
        if row_count > 0:
            parts = []
            for i, row in enumerate(results, 1):
                parts.append(f"--- Row {i} ---")
                row_str = ", ".join(f"{k}: {str(v) if v is not None else 'NULL'}" for k, v in row.items())
                parts.append(row_str)
            raw_context = "\n".join(parts)
            
        return {
            "sql_query": {
                "row_count": row_count,
                "raw_context": raw_context
            }
        }
    except Exception as e:
        print(f"[sql_query_db_call_node] Execution error: {e}")
        return {
            "sql_query": {
                "row_count": 0,
                "raw_context": f"Error: {e}"
            }
        }