# Generated by Django 6.0.5 on 2026-10-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedAnswerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(db_index=True, max_length=255, unique=True)),
                ('psid', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'answer_bot_processed_messages',
                'indexes': [models.Index(fields=['created_at'], name='answer_bot__created_f1ae28_idx')],
            },
        ),
    ]
