# Generated by Django 6.0.5 on 2026-08-23 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityDocuments',
            fields=[
                ('priority_id', models.AutoField(primary_key=True, serialize=False)),
                ('priority_order', models.IntegerField(default=0)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('document', models.ForeignKey(db_column='doc_id', on_delete=django.db.models.deletion.CASCADE, to='rag_api.documents')),
            ],
            options={
                'verbose_name': 'Priority Document',
                'verbose_name_plural': 'Priority Documents',
                'db_table': 'priority_documents',
                'ordering': ['priority_order', '-created_at'],
                'managed': True,
                'unique_together': {('document',)},
            },
        ),
    ]
