# Generated by Django 6.0.7

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FiwanoConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=255)),
                ('sender_id', models.CharField(max_length=255)),
                ('first_message_at', models.DateTimeField(auto_now_add=True)),
                ('last_message_at', models.DateTimeField(auto_now=True)),
                ('message_count', models.IntegerField(default=0)),
                ('chat_history', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-last_message_at'],
                'unique_together': {('channel_id', 'sender_id')},
            },
        ),
        migrations.CreateModel(
            name='FiwanoInboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('channel_id', models.CharField(db_index=True, max_length=255)),
                ('channel_type', models.CharField(max_length=50)),
                ('sender_id', models.CharField(db_index=True, max_length=255)),
                ('sender_name', models.CharField(blank=True, max_length=255, null=True)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('document', 'Document'), ('share', 'Share'), ('unsupported', 'Unsupported')], max_length=50)),
                ('message_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='received', max_length=20)),
                ('response_text', models.TextField(blank=True)),
                ('response_sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('raw_payload', models.JSONField(default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddIndex(
            model_name='fiwanoconversation',
            index=models.Index(fields=['channel_id', 'sender_id'], name='fiwano_bot__channel_f7c8b8_idx'),
        ),
        migrations.AddIndex(
            model_name='fiwanoconversation',
            index=models.Index(fields=['-last_message_at'], name='fiwano_bot__last_me_9e7f1d_idx'),
        ),
        migrations.AddIndex(
            model_name='fiwanoinboundmessage',
            index=models.Index(fields=['channel_id', 'sender_id', '-received_at'], name='fiwano_bot__channel_c8a2d1_idx'),
        ),
        migrations.AddIndex(
            model_name='fiwanoinboundmessage',
            index=models.Index(fields=['status', 'received_at'], name='fiwano_bot__status_e5b9c3_idx'),
        ),
    ]
