# Generated by Django 6.0.5 on 2026-10-08 18:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiwano_bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fiwanoconversation',
            new_name='fiwano_bot__channel_211b38_idx',
            old_name='fiwano_bot__channel_f7c8b8_idx',
        ),
        migrations.RenameIndex(
            model_name='fiwanoconversation',
            new_name='fiwano_bot__last_me_361410_idx',
            old_name='fiwano_bot__last_me_9e7f1d_idx',
        ),
        migrations.RenameIndex(
            model_name='fiwanoinboundmessage',
            new_name='fiwano_bot__channel_aefd3c_idx',
            old_name='fiwano_bot__channel_c8a2d1_idx',
        ),
        migrations.RenameIndex(
            model_name='fiwanoinboundmessage',
            new_name='fiwano_bot__status_733212_idx',
            old_name='fiwano_bot__status_e5b9c3_idx',
        ),
        migrations.AlterField(
            model_name='fiwanoconversation',
            name='first_message_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='fiwanoconversation',
            name='last_message_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='fiwanoinboundmessage',
            name='received_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
