"""
Django settings for cnpi_api project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# cnpi_api/  (this is the Django project dir)
BASE_DIR = Path(__file__).resolve().parent.parent

# Project root = G:\CNPI_Hybrid_RAG  (parent of cnpi_api/)
PROJECT_ROOT = BASE_DIR.parent

# ---------------------------------------------------------------------------
# Add project root, Cnpi_RAG, and plan/ to Python path so the graph
# imports resolve.  PROJECT_ROOT is needed so that `plan` and `Cnpi_RAG`
# resolve as namespace packages (from plan.state import ... / from Cnpi_RAG...).
# _PLAN_DIR is needed so that bare `from state import ...` works (used by
# the node files themselves).
# ---------------------------------------------------------------------------
_CNPI_RAG_DIR = str(PROJECT_ROOT / "Cnpi_RAG")
_PLAN_DIR = str(PROJECT_ROOT / "plan")
for _p in [str(PROJECT_ROOT), _CNPI_RAG_DIR, _PLAN_DIR]:
    if _p not in sys.path:
        sys.path.insert(0, _p)

# ---------------------------------------------------------------------------
# Load .env from project root BEFORE anything imports RAG code
# ---------------------------------------------------------------------------
from dotenv import load_dotenv

load_dotenv(PROJECT_ROOT / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", os.getenv("SECRET_KEY", "django-insecure-fallback-key-change-me"))

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True").lower() in ("true", "1", "yes")

# ALLOWED_HOSTS — production
ALLOWED_HOSTS = ["*"]
# ALLOWED_HOSTS = ["*"] if DEBUG else [
#     "localhost",
#     "127.0.0.1",
#     ".onrender.com",
#     ".hf.space",
#     ".netlify.app",
#     "cnpi-hybrid-rag-1.onrender.com",
#     "warm-fenglisu-e6e0f6.netlify.app",
#     "cnpichat.netlify.app",
# ]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party
    'rest_framework',
    'corsheaders',
    # Local
    'rag_api',
    'admin_panel',
    'messenger_bot',
    'answer_bot',
    'manychat_api',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'admin_panel.middleware.AdminAuthenticationMiddleware',  # Admin panel protection
]

ROOT_URLCONF = 'cnpi_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cnpi_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# NOTE: The RAG system talks to PostgreSQL directly via psycopg2 (see Cnpi_RAG/utils/db_utils.py).
#       Django also connects to the same Neon PostgreSQL for admin/models.

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'neondb'),
        'USER': os.getenv('DB_USER', 'neondb_owner'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT', '5432'),
        # =====================================================================
        # CONNECTION POOLING OPTIMIZATION
        # =====================================================================
        # CONN_MAX_AGE: Keep database connections alive for reuse (seconds)
        #   - 0 (default): Close connection after each request (slow)
        #   - 600: Reuse connections for 10 minutes (50-80s faster)
        #   - None: Keep connections forever (not recommended)
        'CONN_MAX_AGE': int(os.getenv('CONN_MAX_AGE', '600')),
        
        # ATOMIC_REQUESTS: Wrap each view in a transaction (optional)
        'ATOMIC_REQUESTS': False,
        
        'OPTIONS': {
            'sslmode': os.getenv('DB_SSLMODE', 'require'),
            # Connection timeout (5 seconds)
            'connect_timeout': int(os.getenv('DB_CONNECT_TIMEOUT', '5')),
            # Note: statement_timeout removed - Neon pooled connections don't support it
            # Set statement_timeout per-query instead using SET LOCAL if needed
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Dhaka'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Collect static files to a single directory (needed for production)
STATIC_ROOT = BASE_DIR / 'staticfiles'


# ---------------------------------------------------------------------------
# Django REST Framework
# ---------------------------------------------------------------------------
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
}


# ---------------------------------------------------------------------------
# CORS — allow all origins in dev (tighten for production)
# ---------------------------------------------------------------------------
# CORS_ALLOWED_ORIGINS = [
#     "https://cnpichat.netlify.app",
#     "https://warm-fenglisu-e6e0f6.netlify.app",
#     'http://localhost:3000',
# ]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = True

# ---------------------------------------------------------------------------
# ---------------------------------------------------------------------------
# Google OAuth Configuration (API-based, no redirect)
# ---------------------------------------------------------------------------
GOOGLE_CLIENT_ID = os.getenv('GOOGLE_CLIENT_ID', '')

# Only allow specific email domains for admin panel
ADMIN_ALLOWED_EMAILS = os.getenv('ADMIN_ALLOWED_EMAILS', '').split(',')

# ---------------------------------------------------------------------------
# Security Settings - HTTPOnly Cookies
# ---------------------------------------------------------------------------
SESSION_COOKIE_HTTPONLY = True  # JavaScript can't access session cookie
SESSION_COOKIE_SECURE = not DEBUG  # Only send cookie over HTTPS in production
SESSION_COOKIE_SAMESITE = 'Lax'  # CSRF protection
SESSION_COOKIE_AGE = 86400  # 24 hours

CSRF_COOKIE_HTTPONLY = True  # JavaScript can't access CSRF cookie
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SAMESITE = 'Lax'

# Additional security headers
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# Production HTTPS settings (only if not DEBUG)
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# ---------------------------------------------------------------------------
# Render public URL
# ---------------------------------------------------------------------------
# Render automatically sets RENDER_EXTERNAL_URL.  We also accept a manual
# RENDER_PUBLIC_URL override (set in .env.render / Render Environment tab).
RENDER_PUBLIC_URL = (
    os.getenv("RENDER_PUBLIC_URL")
    or os.getenv("RENDER_EXTERNAL_URL")
    or ""
)

# ---------------------------------------------------------------------------
# Heartbeat / Keep-Alive
# ---------------------------------------------------------------------------
# Secret sent in the X-Heartbeat-Secret header by cron callers.
# Set a strong random value in production; leave blank for local dev.
# Generate: python -c "import secrets; print(secrets.token_urlsafe(32))"
HEARTBEAT_SECRET = os.getenv("HEARTBEAT_SECRET", "")

# The URL that heartbeat management command / service will ping.
HEARTBEAT_TARGET_URL = os.getenv(
    "HEARTBEAT_TARGET_URL",
    f"{RENDER_PUBLIC_URL}/api/ping/" if RENDER_PUBLIC_URL else "",
)

# ---------------------------------------------------------------------------
# Facebook Messenger Webhook (Document Saver Bot)
# ---------------------------------------------------------------------------
# FB_VERIFY_TOKEN   : any random string you choose; put it in Meta dashboard
# FB_APP_SECRET     : Meta App Settings > Basic > App Secret
# FB_PAGE_ACCESS_TOKEN : Page Access Token from Messenger settings
# FB_ALLOWED_PSIDS  : comma-separated Page-Scoped User IDs allowed to send messages
#                     e.g. "123456789,987654321"
FB_VERIFY_TOKEN = os.getenv("FB_VERIFY_TOKEN", "")
FB_APP_SECRET = os.getenv("FB_APP_SECRET", "")
FB_PAGE_ACCESS_TOKEN = os.getenv("FB_PAGE_ACCESS_TOKEN", "")
FB_ALLOWED_PSIDS = os.getenv("FB_ALLOWED_PSIDS", "")

# ---------------------------------------------------------------------------
# Answer Bot Webhook (RAG-powered Q&A Bot)
# ---------------------------------------------------------------------------
# Separate Facebook Page/App for Answer Bot
# ANSWER_BOT_VERIFY_TOKEN   : verification token for Answer Bot webhook
# ANSWER_BOT_APP_SECRET     : App Secret for Answer Bot
# ANSWER_BOT_PAGE_ACCESS_TOKEN : Page Access Token for Answer Bot
# ANSWER_BOT_ALLOWED_PSIDS  : comma-separated PSIDs (leave empty to allow all)
# RAG_API_URL               : RAG API endpoint (default: local http://127.0.0.1:8000/api/chat/)
ANSWER_BOT_VERIFY_TOKEN = os.getenv("ANSWER_BOT_VERIFY_TOKEN", "")
ANSWER_BOT_APP_SECRET = os.getenv("ANSWER_BOT_APP_SECRET", "")
ANSWER_BOT_PAGE_ACCESS_TOKEN = os.getenv("ANSWER_BOT_PAGE_ACCESS_TOKEN", "")
ANSWER_BOT_ALLOWED_PSIDS = os.getenv("ANSWER_BOT_ALLOWED_PSIDS", "")
RAG_API_URL = os.getenv("RAG_API_URL", "http://127.0.0.1:8000/api/chat/")

# ---------------------------------------------------------------------------
# Logging — ensure messenger_bot logs appear in Render regardless of DEBUG
# ---------------------------------------------------------------------------
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {
            "format": "%(levelname)s %(name)s: %(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "loggers": {
        "messenger_bot": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "answer_bot": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "WARNING",
    },
}
